import type { Video, User, Comment, Short, Test } from "@/types";

export const users: User[] = [
  { id: 'user-1', name: 'TechVision', avatarUrl: 'https://placehold.co/40x40.png', subscribers: 125000 },
  { id: 'user-2', name: 'GamerGuild', avatarUrl: 'https://placehold.co/40x40.png', subscribers: 78000 },
  { id: 'user-3', name: 'EduLearn', avatarUrl: 'https://placehold.co/40x40.png', subscribers: 250000, teacherId: 'teacher-1' },
  { id: 'user-4', name: 'MusicMania', avatarUrl: 'https://placehold.co/40x40.png', subscribers: 500000 },
  { id: 'user-5', name: 'NewsNow', avatarUrl: 'https://placehold.co/40x40.png', subscribers: 1200000 },
  { id: 'user-6', name: 'AgriSolutions', avatarUrl: 'https://placehold.co/40x40.png', subscribers: 95000, teacherId: 'teacher-2' },
];

export const videos: Video[] = [
  {
    id: 'vid-1',
    title: 'The Future of AI: What to Expect in the Next 5 Years',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'TechVision',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 150000,
    uploadedAt: '2 weeks ago',
    duration: '15:32',
    category: 'Education',
    live: false,
  },
  {
    id: 'vid-2',
    title: 'Epic Gameplay Montage: Best Moments of the Year',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'GamerGuild',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 320000,
    uploadedAt: '1 month ago',
    duration: '10:05',
    category: 'Entertainment',
    live: false,
  },
  {
    id: 'vid-3',
    title: 'Learn JavaScript in 60 Minutes',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'EduLearn',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 1200000,
    uploadedAt: '1 year ago',
    duration: '1:02:15',
    category: 'Education',
    live: false,
  },
  {
    id: 'vid-4',
    title: 'Acoustic Hits: Unplugged Sessions',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'MusicMania',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 850000,
    uploadedAt: '3 months ago',
    duration: '25:40',
    category: 'Music',
    live: false,
  },
  {
    id: 'vid-5',
    title: 'Weekly News Roundup: Top Stories This Week',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'NewsNow',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 95000,
    uploadedAt: '3 days ago',
    duration: '08:12',
    category: 'News',
    live: false,
  },
  {
    id: 'vid-6',
    title: 'Hilarious Cat Fails Compilation',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'GamerGuild',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 2100000,
    uploadedAt: '6 months ago',
    duration: '12:30',
    category: 'Entertainment',
    live: false,
  },
  {
    id: 'vid-7',
    title: 'Quantum Computing Explained Simply',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'TechVision',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 450000,
    uploadedAt: '2 months ago',
    duration: '22:01',
    category: 'Education',
    live: false,
  },
  {
    id: 'vid-8',
    title: 'Top 10 Pop Songs of the Summer - Live Performance',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'MusicMania',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 1500000,
    uploadedAt: '4 days ago',
    duration: '35:50',
    category: 'Music',
    live: true,
  },
  {
    id: 'vid-9',
    title: 'The Science of Cooking: Perfect Steak',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'EduLearn',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 650000,
    uploadedAt: '5 months ago',
    duration: '18:45',
    category: 'Education',
    live: false,
  },
  {
    id: 'vid-10',
    title: 'Indie Gems: A Video Game Review',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'GamerGuild',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 98000,
    uploadedAt: '1 week ago',
    duration: '14:22',
    category: 'Entertainment',
    live: false,
  },
  {
    id: 'vid-11',
    title: 'Breaking News: Market Update',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'NewsNow',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 15000,
    uploadedAt: '2 hours ago',
    duration: '05:30',
    category: 'News',
    live: true,
  },
  {
    id: 'vid-12',
    title: 'Lo-Fi Beats to Relax/Study to',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'MusicMania',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 12000000,
    uploadedAt: '1 year ago',
    duration: '2:30:00',
    category: 'Music',
    live: true,
  },
  {
    id: 'vid-13',
    title: 'Introduction to Sustainable Farming',
    thumbnailUrl: 'https://placehold.co/600x400.png',
    channelName: 'AgriSolutions',
    channelAvatarUrl: 'https://placehold.co/40x40.png',
    views: 75000,
    uploadedAt: '1 day ago',
    duration: '30:15',
    category: 'Education',
    live: false,
  }
];

export const shorts: Short[] = [
    {
      id: 'short-1',
      title: 'Quick Cooking Tip: Perfect Poached Egg',
      thumbnailUrl: 'https://placehold.co/300x500.png',
      channelName: 'EduLearn',
      views: 75000,
    },
    {
      id: 'short-2',
      title: 'Mind-Blowing Optical Illusion!',
      thumbnailUrl: 'https://placehold.co/300x500.png',
      channelName: 'TechVision',
      views: 120000,
    },
    {
      id: 'short-3',
      title: '30-Second Guitar Riff Lesson',
      thumbnailUrl: 'https://placehold.co/300x500.png',
      channelName: 'MusicMania',
      views: 250000,
    },
    {
      id: 'short-4',
      title: 'This Game Is... Different',
      thumbnailUrl: 'https://placehold.co/300x500.png',
      channelName: 'GamerGuild',
      views: 95000,
    },
    {
      id: 'short-5',
      title: 'Cutest Puppy Moment of the Week',
      thumbnailUrl: 'https://placehold.co/300x500.png',
      channelName: 'GamerGuild',
      views: 500000,
    },
    {
        id: 'short-6',
        title: 'Unboxing the New Tech Gadget',
        thumbnailUrl: 'https://placehold.co/300x500.png',
        channelName: 'TechVision',
        views: 320000,
    }
  ];
  

export const comments: Comment[] = [
    { id: 'com-1', user: users[1], text: 'Great video, learned a lot!', timestamp: '2 hours ago' },
    { id: 'com-2', user: users[3], text: 'Awesome content as always!', timestamp: '5 hours ago' },
    { id: 'com-3', user: users[0], text: 'Can you do a video on React hooks next?', timestamp: '1 day ago' },
];

export const tests: Test[] = [
    {
        id: 'test-1',
        subject: 'Mathematics',
        durationInMinutes: 90,
        questions: [
            {
                id: 1,
                question: 'What is 2 + 2?',
                options: ['3', '4', '5', '6'],
                correctAnswer: '4',
            },
            {
                id: 2,
                question: 'What is the square root of 16?',
                options: ['2', '4', '8', '16'],
                correctAnswer: '4',
            },
             {
                id: 3,
                question: 'What is the value of Pi (to 2 decimal places)?',
                options: ['3.14', '3.15', '3.16', '3.17'],
                correctAnswer: '3.14',
            },
        ],
    },
];
